export default {
    Ministers: "அமைச்சர்கள்",
    Add_Ministers: "சேர்_அமைச்சர்கள்",
    First_Name: "முதல் பெயர்",
    Last_Name: "கடைசி பெயர்",
    Email: "மின்னஞ்சல்",
    Mobile_Number: "கைபேசி எண்",
    Vidhansabha: "சட்டசபை",
    Constituency: "தொகுதி",
    Mantralaya: "அமைச்சகம்",
    Status: "நிலை",
    Profile_Picture: "சுயவிவர படம்",
    create: "உருவாக்க",
    Select_Vidhansabha: "தேர்வு சட்டசபை",
    Select_Constituency: "தொகுதியைத் தேர்ந்தெடுக்கவும்",
    Select_Mantralaya: "அமைச்சகத்தை தேர்ந்தெடுக்கவும்",
    Select_Status: "நிலையைத் தேர்ந்தெடுக்கவும்",
    Name: "பெயர்",
    added_on: "சேர்க்கப்பட்டது",
    User: "பயனர்",
    User_Name: "பயனர் பெயர்",
    Minister_Name: "அமைச்சர் பெயர்",
    Last_activity: "கடைசி செயல்பாடு",
    ID: "ஐடி",
    Add_Users: "பயனர்களைச் சேர்க்கவும்",
    filter: "வடிகட்டி",
    search: "தேடல்",
    Language: "மொழி",
    Role: "பங்கு",
    Password: "கடவுச்சொல்",
    Select_Language: "மொழியை தேர்ந்தெடுங்கள்",
    Select_Role: "பாத்திரத்தைத் தேர்ந்தெடுக்கவும்",
    Visits: "வருகைகள்",
    Export: "ஏற்றுமதி",
    Add_Visit: "வருகையைச் சேர்க்கவும்",
    Visit_Type: "வருகை வகை",
    Single: "ஒற்றை",
    Group: "குழு",
    Date_of_birth: "பிறந்த தேதி",
    Gender: "பாலினம்",
    Male: "ஆண்",
    Female: "பெண்",
    Physically_Disabled: "உடல் ஊனமுற்றவர்",
    Yes: "ஆம் ",
    No: "இல்லை ",
    Select_Minister: "அமைச்சரைத் தேர்ந்தெடுக்கவும்",
    Refrence: "குறிப்புகள்",
    Reason_to_visit: "வருகைக்கான காரணம்",
    Media: "ஊடகம்",
    Appoinment_Schedule: "நியமன அட்டவணை ",
    Upload_Appoinments: "நியமனங்களைப் பதிவேற்றவும் ",
    Choose_Files: "கோப்புகளைத் தேர்ந்தெடுக்கவும்",
    only_CSV_file_accepted: "CSV கோப்பு மட்டுமே ஏற்றுக்கொள்ளப்பட்டது",
    Submit: "சமர்ப்பிக்கவும்",
    Cancel: "ரத்து செய்",
    logout: "வெளியேறு",
    Appoinments: " நியமனங்கள்",
    Change_Language: "மொழியை மாற்றவும்",
    Dashboard: "டாஷ்போர்டு",
    Visitors_trend: "பார்வையாளர்களின் போக்கு",
    Vidhansabha_Segments: "சட்டசபை பிரிவுகள்",
    Total_Engagement_Time:"மொத்த நிச்சயதார்த்த நேரம்",
    Admin:"நிர்வாகம்",
    Month:'மாதம்',
    Total_Visitors:'மொத்த பார்வையாளர்கள்',
    Email_address:'மின்னஞ்சல் முகவரி ',
    Are_you_sure_you_want_to_add_user:'பயனரைச் சேர்க்க விரும்புகிறீர்களா?',
    Visit_Timeline:'காலவரிசையைப் பார்வையிடவும்',
    localization:"உள்ளூர்மயமாக்கல்",
    Language_name:'மொழி பெயர்',
    Add_language:'மொழியைச் சேர்க்கவும்',
    Edit_language:'மொழியைத் திருத்து',
    label_translations:'லேபிள் மொழிபெயர்ப்பு',
    import:'இறக்குமதி',
    My_Profile:'என் சுயவிவரம்',
    On_field:'களத்தில்',
    Public_Meetings:'பொதுக் கூட்டங்கள்',
    field_visits:'புலம் பார்வைகள்',
    office:'அலுவலகம்',
    Jasdan:'ஜாஸிடமிருந்து',
    Residence:'குடியிருப்பு',
    visit_details:'வருகை விவரங்கள்',
    mark_as_completed:'முடிந்ததாகக் குறிக்கவும்',
    Engagement_time:'நிச்சயதார்த்த நேரம்',
    added:'சேர்க்கப்பட்டது',
    verify_otp:'otp ஐ சரிபார்க்கவும்',
    we_have_sent_an_otp_to_visitors_mobile_number:'பார்வையாளர்களின் மொபைல் எண்ணுக்கு OTP அனுப்பியுள்ளோம்',
    login:'உள்நுழைய',
    didnot_received_otp_resend_in:'OTP மீண்டும் அனுப்பப்படவில்லை',
    forgot_password:'கடவுச்சொல்லை மறந்துவிட்டீர்களா',
    reset_password:'கடவுச்சொல்லை மீட்டமைக்க',
    thank_you:'நன்றி',
    super_admin:'சூப்பர் அட்மின்',
    send_weekly_visit_report:'வாராந்திர வருகை அறிக்கையை அனுப்பவும்',
    Upload:'பதிவேற்றவும்',
    import_label_translation:'லேபிள் மொழிபெயர்ப்பை இறக்குமதி செய்யவும்',
    browse:'உலவ',
  };