export default {
  Ministers: "मंत्रियों",
  Add_Ministers: "मंत्रियों को जोड़ें",
  First_Name: "पहला नाम",
  Last_Name: "उपनाम",
  Email: "ईमेल",
  Mobile_Number: "मोबाइल नंबर",
  Vidhansabha: "विधानसभा",
  Constituency: "चुनाव क्षेत्र",
  Mantralaya: "मंत्रालय",
  Status: "दर्जा",
  Profile_Picture: "प्रोफ़ाइल फोटो",
  create: "क्रिएट",
  Select_Vidhansabha: "विधानसभा का चयन करें",
  Select_Constituency: "निर्वाचन क्षेत्र का चयन करें",
  Select_Mantralaya: "मंत्रालय का चयन करें",
  Select_Status: "स्थिति चुनें",
  Name: "नाम",
  added_on: "पर जोड़ा",
  User: "उपयोगकर्ता",
  User_Name: "उपयोगकर्ता नाम",
  Minister_Name: "मंत्री का नाम",
  Last_activity: "आख़िरी गतिविधि",
  ID: "आईडी",
  Add_Users: "उपयोगकर्ता जोड़ें",
  filter: "फ़िल्टर",
  search: "सर्च",
  Language: "भाषा",
  Role: "भूमिका",
  Password: "पासवर्ड",
  Select_Language: "भाषा चुने",
  Select_Role: "भूमिका चुनें",
  Visits: "विजिट",
  Export: "निर्यात",
  Add_Visit: "विजिट जोड़ें",
  Visit_Type: "विज़िट प्रकार",
  Single: "सिंगल",
  Group: "समूह",
  Date_of_birth: "जन्म तिथि",
  Gender: "लिंग",
  Male: "पुस्र्ष",
  Female: "महिला",
  Physically_Disabled: "फिजिकल डिसेबिलिटी",
  Yes: "हाँ",
  No: "नहीं",
  Select_Minister: "मंत्री चुनें",
  Refrence: "रेफ़्रेन्स",
  Reason_to_visit: "यात्रा करने का कारण",
  Media: "मिडिया",
  Appoinment_Schedule: "नियुक्ति अनुसूची",
  Upload_Appoinments: "अपॉइंटमेंट अपलोड करें",
  Choose_Files: "फ़ाइलों का चयन करें",
  only_CSV_file_accepted: "केवल CSV फ़ाइल स्वीकार की गई",
  Submit: "सम्मिट",
  Cancel: "रद्द करें",
  logout: "लॉग आउट",
  Appoinments: "अपॉइंटमेंट",
  Change_Language: "भाषा बदलें",
  Dashboard: "डैशबोर्ड",
  Visitors_trend: "विजिटर्स का रुझान",
  Vidhansabha_Segments: "विधानसभा सेग्मेंट्स",
  Total_Engagement_Time:'कुल इंगेजमेंट समय',
  Admin:'एडमिन',
  Month:'महीना',
  Total_Visitors:'कुल विजिटर्स',
  Email_address:'ई-मेल एड्रेस',
  Are_you_sure_you_want_to_add_user:'क्या आप वाकई उपयोगकर्ता जोड़ना चाहते हैं?',
  Visit_Timeline:'समयरेखा पर जाएँ',
  localization:"लोकलज़ैशन",
  Language_name:'भाषा का नाम',
  Add_language:'भाषा जोड़ें',
  Edit_language:'भाषा संपादित करें',
  label_translations:'लेबल अनुवाद',
  import:'आयात',
  My_Profile:'मेरी प्रोफाइल',
  On_field:'मैदान पर',
  Public_Meetings:'सार्वजनिक बैठकें',
  field_visits:'क्षेत्र का दौरा',
  office:'कार्यालय',
  Jasdan:'जसदण',
  Residence:'निवास स्थान',
  visit_details:'यात्रा विवरण',
  mark_as_completed:'पूर्ण के रूप में चिह्नित करें',
  Engagement_time:'इंगेजमेंट समय',
  added:'जोड़ा',
  verify_otp:'ओटीपी सत्यापित करें',
  we_have_sent_an_otp_to_visitors_mobile_number:'हमने आगंतुकों के मोबाइल नंबर पर एक ओटीपी भेजा है',
  login:'लॉग इन',
  didnot_received_otp_resend_in:'ओटीपी नहीं मिला फिर से भेजें',
  forgot_password:'पासवर्ड भूल गए',
  reset_password:'पासवर्ड रीसेट',
  thank_you:'धन्यवाद',
  super_admin:'सुपर एडमिन',
  send_weekly_visit_report:'साप्ताहिक यात्रा रिपोर्ट भेजें',
  Upload:'अपलोड',
  import_label_translation:'आयात लेबल अनुवाद',
  browse:'ब्राउज़',
};
