export default {
    Ministers: "మంత్రులు",
    Add_Ministers: "మంత్రులను చేర్చుకోండి",
    First_Name: "మొదటి పేరు",
    Last_Name: "చివరి పేరు",
    Email: "ఇమెయిల్",
    Mobile_Number: "మొబైల్ నంబర్",
    Vidhansabha: "అసెంబ్లీ",
    Constituency: "నియోజకవర్గం",
    Mantralaya: "మంత్రిత్వ శాఖ",
    Status: "స్థితి",
    Profile_Picture: "ప్రొఫైల్ చిత్రం",
    create: "సృష్టించు",
    Select_Vidhansabha: "అసెంబ్లీని ఎంచుకోండి",
    Select_Constituency: "నియోజకవర్గాన్ని ఎంచుకోండి",
    Select_Mantralaya: "మంత్రిత్వ శాఖను ఎంచుకోండి",
    Select_Status: "స్థితిని ఎంచుకోండి",
    Name: "పేరు",
    added_on: "జోడించబడింది",
    User: "వినియోగదారు",
    User_Name: "వినియోగదారు పేరు",
    Minister_Name: "మంత్రి పేరు",
    Last_activity: "చివరి కార్యాచరణ",
    ID: "ఇది",
    Add_Users: "వినియోగదారులను జోడించండి",
    filter: "వడపోత",
    search: "వెతకండి",
    Language: "భాష",
    Role: "పాత్ర",
    Password: "పాస్వర్డ్",
    Select_Language: "భాషను ఎంచుకోండి",
    Select_Role: "పాత్రను ఎంచుకోండి",
    Visits: "సందర్శనలు",
    Export: "ఎగుమతి చేయండి",
    Add_Visit: "సందర్శనను జోడించండి",
    Visit_Type: "సందర్శన రకం",
    Single: "సింగిల్",
    Group: "సమూహం",
    Date_of_birth: "పుట్టిన తేది",
    Gender: "లింగం",
    Male: "పురుషుడు",
    Female: "స్త్రీ",
    Physically_Disabled: "శారీరక వికలాంగుడు",
    Yes: "అవును",
    No: "నం",
    Select_Minister: "మంత్రిని ఎంపిక చేసుకోండి",
    Refrence: "సూచన",
    Reason_to_visit: "సందర్శించడానికి కారణం",
    Media: "మీడియా",
    Appoinment_Schedule: "అపాయింట్‌మెంట్ షెడ్యూల్",
    Upload_Appoinments: "అపాయింట్‌మెంట్‌ని అప్‌లోడ్ చేయండి",
    Choose_Files: "ఫైల్‌ని ఎంచుకోండి",
    only_CSV_file_accepted: "CSV ఫైల్ మాత్రమే ఆమోదించబడింది",
    Submit: "సమర్పించండి",
    Cancel: "రద్దు చేయండి",
    logout: "లాగ్అవుట్",
    Appoinments: "నియామకాలు",
    Change_Language: "భాష మార్చు",
    Dashboard: "డాష్బోర్డ్",
    Visitors_trend: "సందర్శకుల ట్రెండ్",
    Vidhansabha_Segments: "విధానసభ సెగ్మెంట్లు",
    Total_Engagement_Time:'మొత్తం నిశ్చితార్థం సమయం',
    Admin:'అడ్మిన్',
    Month:'నెల',
    Total_Visitors:'మొత్తం సందర్శకులు',
    Email_address:'ఇమెయిల్ చిరునామా',
    Are_you_sure_you_want_to_add_user:'మీరు ఖచ్చితంగా వినియోగదారుని జోడించాలనుకుంటున్నారా?',
    Visit_Timeline:'టైమ్‌లైన్‌ని సందర్శించండి',
    localization:"స్థానికీకరణ",
    Language_name:'భాష పేరు',
    Add_language:'భాషను జోడించండి',
    Edit_language:'భాషను సవరించండి',
    label_translations:'లేబుల్ అనువాదాలు',
    import:'దిగుమతి',
    My_Profile:'నా జీవన వివరణ',
    On_field:'ఫీల్డ్‌లో',
    Public_Meetings:'బహిరంగ సభలు',
    field_visits:'క్షేత్ర సందర్శనలు',
    office:'కార్యాలయం',
    Jasdan:'जसदण',
    Residence:'నివాసం',
    visit_details:'సందర్శన వివరాలు',
    mark_as_completed:'పూర్తయినట్లు గుర్తు పెట్టండి',
    Engagement_time:'నిశ్చితార్థం సమయం',
    added:'జోడించారు',
    verify_otp:'otpని ధృవీకరించండి',
    we_have_sent_an_otp_to_visitors_mobile_number:'మేము సందర్శకుల మొబైల్ నంబర్‌కు ఓటీపీని పంపాము',
    login:'ప్రవేశించండి',
    didnot_received_otp_resend_in:'ఓటీపీని మళ్లీ పంపలేదు',
    forgot_password:'పాస్వర్డ్ మర్చిపోయాను',
    reset_password:'రహస్యపదాన్ని మార్చుకోండి',
    thank_you:'ధన్యవాదాలు',
    super_admin:'సూపర్ అడ్మిన్',
    send_weekly_visit_report:'వారంవారీ సందర్శన నివేదికను పంపండి',
    Upload:'అప్‌లోడ్ చేయండి',
    import_label_translation:'లేబుల్ అనువాదం దిగుమతి',
    browse:'బ్రౌజ్ చేయండి',
  };
  