export default {
    Ministers: "ਮੰਤਰੀਆਂ",
    Add_Ministers: "ਮੰਤਰੀਆਂ ਨੂੰ ਸ਼ਾਮਲ ਕਰੋ",
    First_Name: "ਪਹਿਲਾ ਨਾਂ",
    Last_Name: "ਆਖਰੀ ਨਾਂਮ",
    Email: "ਈ - ਮੇਲ",
    Mobile_Number: "ਮੋਬਾਇਲ ਨੰਬਰ",
    Vidhansabha: "ਅਸੈਂਬਲੀ",
    Constituency: "ਚੋਣ ਖੇਤਰ",
    Mantralaya: "ਮੰਤਰਾਲੇ",
    Status: "ਸਥਿਤੀ",
    Profile_Picture: "ਪ੍ਰੋਫਾਈਲ ਪਿਕਚਰ",
    create: "ਬਣਾਓ",
    Select_Vidhansabha: "ਅਸੈਂਬਲੀ ਦੀ ਚੋਣ ਕਰੋ",
    Select_Constituency: "ਚੋਣ ਖੇਤਰ ਚੁਣੋ",
    Select_Mantralaya: "ਮੰਤਰਾਲੇ ਦੀ ਚੋਣ ਕਰੋ",
    Select_Status:"ਸਥਿਤੀ ਚੁਣੋ",
    Name: "ਨਾਮ",
    added_on: "'ਤੇ ਸ਼ਾਮਲ ਕੀਤਾ ਗਿਆ",
    User: "ਉਪਭੋਗਤਾ",
    User_Name: "ਉਪਭੋਗਤਾ ਨਾਮ",
    Minister_Name: "ਮੰਤਰੀ ਦਾ ਨਾਮ",
    Last_activity: "ਪਿਛਲੀ ਗਤੀਵਿਧੀ",
    ID: "ਆਈ.ਡੀ",
    Add_Users: "ਉਪਭੋਗਤਾ ਸ਼ਾਮਲ ਕਰੋ",
    filter: "ਫਿਲਟਰ",
    search: "ਖੋਜ",
    Language: "ਭਾਸ਼ਾ",
    Role: "ਭੂਮਿਕਾ",
    Password: "ਪਾਸਵਰਡ",
    Select_Language: "ਭਾਸ਼ਾ ਚੁਣੋ",
    Select_Role: "ਰੋਲ ਚੁਣੋ",
    Visits: "ਮੁਲਾਕਾਤਾਂ",
    Export: "ਨਿਰਯਾਤ",
    Add_Visit: "ਫੇਰੀ ਸ਼ਾਮਲ ਕਰੋ",
    Visit_Type: "ਕਿਸਮ 'ਤੇ ਜਾਓ",
    Single:  "ਸਿੰਗਲ",
    Group: "ਸਮੂਹ",
    Date_of_birth: "ਜਨਮ ਤਾਰੀਖ",
    Gender: "ਲਿੰਗ",
    Male: "ਨਰ",
    Female: "ਔਰਤ",
    Physically_Disabled:"ਸਰੀਰਕ ਤੌਰ 'ਤੇ ਅਸਮਰੱਥ",
    Yes: "ਹਾਂ",
    No: "ਨੰ",
    Select_Minister: "ਮੰਤਰੀ ਚੁਣੋ",
    Refrence: "ਹਵਾਲੇ",
    Reason_to_visit: "ਮਿਲਣ ਦਾ ਕਾਰਨ",
    Media: "ਮੀਡੀਆ",
    Appoinment_Schedule: "ਮੁਲਾਕਾਤ ਅਨੁਸੂਚੀ",
    Upload_Appoinments: " ਮੁਲਾਕਾਤਾਂ ਅੱਪਲੋਡ ਕਰੋ",
    Choose_Files: "ਫਾਈਲ ਚੁਣੋ",
    only_CSV_file_accepted:"ਸਿਰਫ਼ CSV ਫ਼ਾਈਲ ਸਵੀਕਾਰ ਕੀਤੀ ਜਾਂਦੀ ਹੈ",
    Submit: "ਜਮ੍ਹਾਂ ਕਰੋ",
    Cancel: "ਰੱਦ ਕਰੋ",
    logout: "ਲਾੱਗ ਆਊਟ, ਬਾਹਰ ਆਉਣਾ",
    Appoinments: "ਮੁਲਾਕਾਤਾਂ",
    Change_Language: "ਭਾਸ਼ਾ ਬਦਲੋ",
    Dashboard: "ਡੈਸ਼ਬੋਰਡ",
    Visitors_trend: "ਸੈਲਾਨੀਆਂ ਦਾ ਰੁਝਾਨ",
    Vidhansabha_Segments: "ਅਸੈਂਬਲੀ ਹਿੱਸੇ",
    Total_Engagement_Time:"ਕੁੱਲ ਸ਼ਮੂਲੀਅਤ ਸਮਾਂ",
    Admin:"ਐਡਮਿਨ",
    Month:"ਮਹੀਨਾ",
    Total_Visitors:'ਕੁੱਲ ਵਿਜ਼ਿਟਰ',
    Email_address:'ਈਮੇਲ ਪਤਾ',
    Are_you_sure_you_want_to_add_user:"ਕੀ ਤੁਸੀਂ ਯਕੀਨੀ ਤੌਰ 'ਤੇ ਉਪਭੋਗਤਾ ਨੂੰ ਸ਼ਾਮਲ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
    Visit_Timeline:"ਟਾਈਮਲਾਈਨ 'ਤੇ ਜਾਓ",
    localization:"ਸਥਾਨੀਕਰਨ",
    Language_name:"ਭਾਸ਼ਾ ਦਾ ਨਾਮ",
    Add_language:"ਭਾਸ਼ਾ ਸ਼ਾਮਲ ਕਰੋ",
    Edit_language:"ਭਾਸ਼ਾ ਦਾ ਸੰਪਾਦਨ ਕਰੋ",
    label_translations:"ਲੇਬਲ ਅਨੁਵਾਦ",
    import:' ਆਯਾਤ',
    My_Profile:'ਮੇਰਾ ਪ੍ਰੋਫ਼ਾਈਲ',
    On_field:'ਫੀਲਡ ਤੇ',
    Public_Meetings:' ਜਨਤਕ ਮੀਟਿੰਗਾਂ',
    field_visits:'ਖੇਤਰ ਦੇ ਦੌਰੇ',
    office:'ਦਫ਼ਤਰ',
    Jasdan:'ਜਸ ਤੋਂ',
    Residence:'ਨਿਵਾਸ',
    visit_details:'ਵੇਰਵਿਆਂ ਤੇ ਜਾਓ',
    mark_as_completed:"ਮੁਕੰਮਲ ਵਜੋਂ ਨਿਸ਼ਾਨ ਲਗਾਓ",
    Engagement_time:'ਸ਼ਮੂਲੀਅਤ ਦਾ ਸਮਾਂ',
    added:'ਜੋੜਿਆ ਗਿਆ',
    verify_otp:'otp ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    we_have_sent_an_otp_to_visitors_mobile_number:"ਅਸੀਂ ਵਿਜ਼ਟਰਾਂ ਦੇ ਮੋਬਾਈਲ ਨੰਬਰ 'ਤੇ ਇੱਕ ਓਟੀਪੀ ਭੇਜਿਆ ਹੈ",
    login:"ਲਾਗਿਨ",
    didnot_received_otp_resend_in:' ਓ.ਟੀ.ਪੀ. ਪ੍ਰਾਪਤ ਨਹੀਂ ਹੋਇਆ',
    forgot_password:'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ',
    reset_password:'ਪਾਸਵਰਡ ਰੀਸੈਟ ਕਰੋ',
    thank_you:'ਤੁਹਾਡਾ ਧੰਨਵਾਦ',
    super_admin:'ਸੁਪਰ ਐਡਮਿਨ',
    send_weekly_visit_report:'ਹਫਤਾਵਾਰੀ ਮੁਲਾਕਾਤ ਰਿਪੋਰਟ ਭੇਜੋ',
    Upload:'ਅੱਪਲੋਡ ਕਰੋ',
    import_label_translation:'ਆਯਾਤ ਲੇਬਲ ਅਨੁਵਾਦ',
    browse:'ਬਰਾਊਜ਼ ਕਰੋ',
  };
  
  