export default {
    Ministers: "मंत्री लोग के बा",
    Add_Ministers: "मंत्री लोग के जोड़ल जाव",
    First_Name: "पहिला नांव",
    Last_Name: "अंतिम नाम",
    Email: "ईमेल पर भेजल जा सकेला",
    Mobile_Number: "मोबाइल नंबर बा",
    Vidhansabha: "सभा",
    Constituency: "निर्वाचन क्षेत्र के बा",
    Mantralaya: "मंत्रालय के ह",
    Status: "ओहदा",
    Profile_Picture: "प्रोफाइल के तस्वीर बा",
    create: "बनावल",
    Select_Vidhansabha: "विधानसभा के चयन करीं",
    Select_Constituency: "निर्वाचन क्षेत्र के चयन करीं",
    Select_Mantralaya: "मंत्रालय के चयन करीं",
    Select_Status: "स्टेटस के चयन करीं",
    Name: "नांव",
    added_on: "पर जोड़ल गइल",
    User: "प्रयोगकर्ता के बा",
    User_Name: "प्रयोगकर्ता के नाम बा",
    Minister_Name: "मंत्री के नाम बा",
    Last_activity: "आखिरी गतिविधि के बारे में बतावल गइल बा",
    ID: "आईडी के बा",
    Add_Users: "उपयोगकर्ता लोग के जोड़ल जाला",
    filter: "फिल्टर कइल जाला",
    search: "तलाशी",
    Language: "भाखा",
    Role: "भूमिका",
    Password: "पासवर्ड",
    Select_Language: "भाषा के चयन करीं",
    Select_Role: "भूमिका के चयन करीं",
    Visits: "घूमे-फिरे के बा",
    Export: "निर्यात",
    Add_Visit: "विजिट के जोड़ल जाव",
    Visit_Type: "विजिट के प्रकार के बा",
    Single: "अकेला",
    Group: "समूह",
    Date_of_birth: "जन्म तिथि के बा",
    Gender: "लिंग",
    Male: "मरद",
    Female: "मेहरारू",
    Physically_Disabled: "शारीरिक रूप से विकलांग बाड़े",
    Yes: "हॅंं",
    No: "ना",
    Select_Minister: "मंत्री के चयन करीं",
    Refrence: "संदर्भ दिहल गइल बा",
    Reason_to_visit: "घूमे के कारण बा",
    Media: "मीडिया के ह",
    Appoinment_Schedule: "नियुक्ति के समय सारिणी बा",
    Upload_Appoinments: "अपलोड अपॉइंटमेंट के बा",
    Choose_Files: "अपलोड अपॉइंटमेंट के बा",
    only_CSV_file_accepted: "खाली सीएसवी फाइल के स्वीकार कइल जाला",
    Submit: "जमा करीं",
    Cancel: "मना कइ दीं",
    logout: "लॉगआउट कइल जाला",
    Appoinments: "नियुक्ति भइल बा",
    Change_Language: "भाषा बदले के बा",
    Dashboard: "डैशबोर्ड के बा",
    Visitors_trend: "आगंतुकन के रुझान बा",
    Vidhansabha_Segments: "विधानसभा के खंडन के बारे में बतावल गइल बा",
    Total_Engagement_Time:'कुल सगाई के समय बा',
    Admin:'एडमिन के ह',
    Month:'महीना',
    Total_Visitors:'कुल आगंतुक लोग के बा',
    Email_address:'ईमेल के पता बा',
    Are_you_sure_you_want_to_add_user:'का रउआँ पक्का बानी कि रउआँ यूजर जोड़ल चाहत बानी?',
    Visit_Timeline:'टाइमलाइन पर जाईं',
    localization:"स्थानीयकरण के बारे में बतावल गइल बा",
    Language_name:'भाषा के नाम के नाम बा',
    Add_language:'भाषा जोड़ल जाव',
    Edit_language:'भाषा के संपादन करीं',
    label_translations:'लेबल के अनुवाद कइल जाला',
    import:'आयात',
    My_Profile:'हमार प्रोफाइल बा',
    On_field:'फील्ड पर बा',
    Public_Meetings:'जनसभा के आयोजन कइल जाला',
    field_visits:'फील्ड विजिट के बारे में बतावल गइल बा',
    office:'कार्यालय',
    Jasdan:'जसदण',
    Residence:'निवास के बा',
    visit_details:'विस्तार से देखल जाव',
    mark_as_completed:'पूरा भइला के रूप में चिन्हित करीं',
    Engagement_time:'इंगेजमेंट समय',
    added:'जोड़ले बाड़न',
    verify_otp:'ओटीपी के सत्यापन करींरें',
    we_have_sent_an_otp_to_visitors_mobile_number:'हमने आगंतुकों के मोबाइल नंबर पर एक ओटीपी भेजा है',
    login:'लॉगिन हो गइल बा',
    didnot_received_otp_resend_in:'में ओटीपी फिर से भेजल ना मिलल',
    forgot_password:'पासवर्ड भुला गइल बानी',
    reset_password:'पासवर्ड रीसेट करीं',
    thank_you:'धन्यबाद',
    super_admin:'सुपर एडमिन के बा',
    send_weekly_visit_report:'साप्ताहिक यात्रा रिपोर्ट भेजल जाला',
    Upload:'अपलोड कइल जाव',
    import_label_translation:'लेबल अनुवाद के आयात कइल जाला',
    browse:'ब्राउज करे के बा',
  };
  