export default {
    Ministers: "मंत्री",
    Add_Ministers: "मंत्री लोग के जोड़ल जाव",
    First_Name: "पहिले नाव",
    Last_Name: "आडनाव",
    Email: "ईमेल",
    Mobile_Number: "मोबाईल नंबर",
    Vidhansabha: "विधानसभा",
    Constituency: "मतदारसंघ",
    Mantralaya: "मंत्रालय",
    Status: "स्थिती",
    Profile_Picture: "परिचय चित्र",
    create: "तयार करा",
    Select_Vidhansabha: "विधानसभा निवडा",
    Select_Constituency: "मतदारसंघ निवडा",
    Select_Mantralaya: "मंत्रालय निवडा",
    Select_Status: "स्थिती निवडा",
    Name: "नाव",
    added_on: "वर जोडले",
    User: "वापरकर्ता",
    User_Name: "वापरकर्ता नाव",
    Minister_Name: "मंत्र्याचे नाव",
    Last_activity: "शेवटचा क्रियाकलाप",
    ID: "आयडी",
    Add_Users: "वापरकर्ते जोडा",
    filter: "फिल्टर",
    search: "शोध",
    Language: "इंग्रजी",
    Role: "भूमिका",
    Password: "पासवर्ड",
    Select_Language: "भाषा निवडा",
    Select_Role: "भूमिका निवडा",
    Visits: "भेटी",
    Export: "निर्यात करा",
    Add_Visit: "भेट जोडा",
    Visit_Type: "भेट प्रकार",
    Single: "अविवाहित",
    Group: "गट",
    Date_of_birth: "जन्मतारीख",
    Gender: "लिंग",
    Male: "पुरुष",
    Female: "स्त्री",
    Physically_Disabled: "शारीरिकदृष्ट्या अक्षम",
    Yes: "होय",
    No: "नाही",
    Select_Minister: "मंत्री निवडा",
    Refrence: "संदर्भ",
    Reason_to_visit: "भेट देण्याचे कारण",
    Media: "मीडिया",
    Appoinment_Schedule: "भेटीचे वेळापत्रक",
    Upload_Appoinments: "अपॉइंटमेंट अपलोड करा",
    Choose_Files: "फाईल निवडा",
    only_CSV_file_accepted: "फक्त CSV फाइल स्वीकारली",
    Submit: "प्रस्तुत करणे",
    Cancel: "रद्द करा",
    logout: "बाहेर पडणे",
    Appoinments: "भेटी",
    Change_Language: "भाषा बदला",
    Dashboard: "डॅशबोर्ड",
    Visitors_trend: "अभ्यागतांचा कल",
    Vidhansabha_Segments: "विधानसभा विभाग",
    Total_Engagement_Time:'एकूण प्रतिबद्धता वेळ',
    Admin:'अॅडमिन',
    Month:'महिना',
    Total_Visitors:'एकूण अभ्यागत',
    Email_address:'ईमेल पत्ता',
    Are_you_sure_you_want_to_add_user:'तुम्हाला खात्री आहे की तुम्ही वापरकर्ता जोडू इच्छिता?',
    Visit_Timeline:'टाइमलाइनला भेट द्याईं',
    localization:"स्थानिकीकरण",
    Language_name:'भाषेचे नाव',
    Add_language:'भाषा जोडा',
    Edit_language:'भाषा संपादित करा',
    label_translations:'लेबल भाषांतरे',
    import:'आयात',
    My_Profile:'माझे प्रोफाइल',
    On_field:'मैदानावर',
    Public_Meetings:'जाहीर सभा',
    field_visits:'क्षेत्र भेटी',
    office:'कार्यालय',
    Jasdan:'जसदण',
    Residence:'निवासस्थान',
    visit_details:'तपशील भेट द्या',
    mark_as_completed:'पूर्ण झाले म्हणून चिन्हांकित करा',
    Engagement_time:'प्रतिबद्धता वेळ',
    added:'जोडले',
    verify_otp:'otp सत्यापित करा',
    we_have_sent_an_otp_to_visitors_mobile_number:'आम्ही अभ्यागतांच्या मोबाईल नंबरवर एक ओटीपी पाठवला आहे',
    login:'लॉगिन',
    didnot_received_otp_resend_in:'ओटीपी पुन्हा पाठवला नाही',
    forgot_password:'पासवर्ड विसरलात',
    reset_password:'पासवर्ड रीसेट करा',
    thank_you:'धन्यवाद',
    super_admin:'सुपर प्रशासक',
    send_weekly_visit_report:'साप्ताहिक भेट अहवाल पाठवा',
    Upload:'अपलोड करा',
    import_label_translation:'आयात लेबल अनुवाद',
    browse:'ब्राउझ करा',
  };
  